name: Retry release

on:
  workflow_dispatch:
    inputs:
      release_pr:
        description: Release PR number
        required: true
      flags:
        description: Extra flags to pass to the release script
        required: false
        default: ""

permissions:
  contents: read

jobs:
  release-retry:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    env:
      ruby_version: "3.1"
    steps:
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@v1.245.0
        with:
          ruby-version: ${{ env.ruby_version }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Toys
        run: "gem install --no-document toys -v 0.15.5"
      - name: Retry release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release retry --yes --verbose \
            "--enable-releases=${{ secrets.ENABLE_RELEASES }}" \
            "--rubygems-api-key=${{ secrets.RUBYGEMS_API_KEY }}" \
            ${{ github.event.inputs.flags }} \
            "${{ github.event.inputs.release_pr }}" \
            < /dev/null
