name: "[release hook] Update open releases"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-update-open-requests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      ruby_version: "3.1"
    steps:
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@v1.245.0
        with:
          ruby-version: ${{ env.ruby_version }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Toys
        run: "gem install --no-document toys -v 0.15.5"
      - name: Update open releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release _onpush --verbose \
            < /dev/null
